version: '3.9'

services:
  talentmatch:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"  # Puerto para Vite dev server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_DEV_SERVER_HOST=0.0.0.0
    stdin_open: true
    tty: true
    restart: unless-stopped
